### ISSUE TITLE
testr define method not called when running jasmine with htmlunit

### ISSUE THREAD

**Issue by ghost** [mattfysh/testr.js#5]
Hi,

I am currently trying to use testr to test modules using the maven jasmine plugin. Everything works fine when I run the jasmine tests via the browser, however when I run the tests in headless mode the overriden define method is not called and the actual require.js module with its actual dependencies are returned rather than the stubbed dependencies.

Regards
Brian

**Comment by ghost** [comment]
Hi, 

I have managed to work around this issue, I am not sure whether it is a problem with testr or with the way in which htmlunit executes scripts (I suspect the later). 

What seems to happen is that when running in a browser, the testr.js script, which is included after the require.js script (which includes the data-main attribute), runs before the data-main script which allows testr to override the define function. 

However, when running in headless mode with htmlunit, what happens is that the data-main script seems to run before the testr script, which means that testr has not had a chance to override the define function and as a result the following code is executed when you request a module :

if (!moduleDef) {
    // module may be stored in requirejs, e.g. plugin-loaded dependencies
    try {
        // THIS CODE GETS EXECUTED RETURNING THE ACTUAL DEPENDENCIES
        return require(moduleName);
    } catch(e) {
        throw new Error('module has not been loaded: ' + moduleName);
    }
}

The work around is to not use the data-main attribute, but rather to specify a script in the body that specifies the require.js config and then calls require. Internally to require you then setup jasmine and execute the specs. This means that the testr.js script will have a chance to run and override the define function before the require call.

Regards
Brian

**Comment by mattfysh** [comment]
Hi Brian,

I'll take a look at this over the weekend. I may need to shadow the document.createElement method in this case, but fundamentally it seems to be a runtime-specific issue. That is, some browsers will let Require JS add and execute JavaScript in a blocking manner before the rest of the page is loaded.

Cheers,
Matt.

**Comment by ghost** [comment]
Interesting. Does that imply that there is a possibility that require.js will start loading modules before testr has a chance to overwrite the define function?

**Comment by mattfysh** [comment]
@gurrie I've updated the readme with the recommended approach. Avoid pre-defining the `require` object, and also avoid using the `data-main` attribute, as these may lead to modules being loaded before testr.js has a chance to monkey-patch the `require` and `define` methods.

Here's how you should setup your test page:

``` html
<script src="require.js"></script>
<script src="testr.js"></script>
<script>
  require(['mod1', 'mod2', 'mod3'], function() {
    var module = testr('mod1');
    // etc ..
  }
</script>
```
