### ISSUE TITLE
a jstestdriver example would be useful

### ISSUE THREAD

**Issue by acthp** [mattfysh/testr.js#7]
jstestdriver test cases don't work if require() has to do an async load. The modules have to be pre-loaded. But I haven't found a way to get jstestdriver to wait for requirejs to finish loading modules. It starts loading test cases before requirejs is finished.

E.g. if the config is

load
- require.js
- require-config.js

test
- atestcase.js

and require-config.js has deps: [ 'mymodule' ], then atestcase.js will load before mymodule.js, causing requirejs to do an async fetch of mymodule.js, and then the TestCase registration fails.

**Comment by mattfysh** [comment]
I'll take a look at this later on, just quickly though - does setting a timeout in the JsTestDriver config have any effect?

**Comment by acthp** [comment]
Nope. If I understand it correctly, the timeout is for aborting test cases, e.g. if a test hangs. I just tried it for good measure. No effect on load timing problems.

There are a couple jstestdriver plugin hooks that might be able to solve it, by blocking a test or suite until the loading is finished.

**Comment by acthp** [comment]
Digging into this more, I don't think there's a way to reliably preload without additional support. I think at best you create a race condition between requirejs and jstestdriver, which are both asynchronously loading scripts. To do it reliably, jstestdriver has to be aware of when requirejs is finished loading.

I was able to get it to work outside of testr.js by writing a loadScript plugin for jstestdriver:

https://gist.github.com/3557646

**Comment by mattfysh** [comment]
@acthp there is some info on setting up asynchronous test cases at http://code.google.com/p/js-test-driver/wiki/AsyncTestCase

Use the callback for your initial require call to know when to kick off the tests. Once requireJS has loaded all of your module definitions, the rest of your tests will be synchronous, as long as they don't use lazy loaded modules.
